version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: donaton-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  auths:
    build: ./MicroS-Auth
    container_name: micros-auths
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  necesidades:
    build: ./MicroS-Necesidades
    container_name: micros-necesidades
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy

  donaciones:
    build: ./MicroS-Donaciones
    container_name: micros-donaciones
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy

  logistica:
    build: ./MicroS-Logistica
    container_name: micros-logistica
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
