spring.application.name=MicroS-Logistica

# Conexión a MySQL dentro de Docker
spring.datasource.url=jdbc:mysql://mysql:3306/logistica_db
spring.datasource.username=logistica
spring.datasource.password=logistica123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
